RANDOM1:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    - GAYGO1
    - GAYGO2
    - GAYGO3
    - GAYGO4
    - GAYGO5
RANDOM2:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    - GAYGO3
    - GAYGO4
    - GAYGO5
    - GAYGO6
    - GAYGO7
RANDOM3:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    - GAYGO5
    - GAYGO6
    - GAYGO7
    - GAYGO8
    - GAYGO9
RANDOM4:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    - GAYGO7
    - GAYGO8
    - GAYGO9
    - GAYGO10
    - GAYGO11
RANDOM5:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    - GAYGO9
    - GAYGO10
    - GAYGO11
    - GAYGO12
    - GAYGO13
RANDOM6:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    - GAYGO11
    - GAYGO12
    - GAYGO13
    - GAYGO14
    - GAYGO15
RANDOM7:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    - GAYGO13
    - GAYGO14
    - GAYGO15
    - GAYGO16
    - GAYGO17
RANDOM8:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    - GAYGO15
    - GAYGO16
    - GAYGO17
    - GAYGO18
    - GAYGO19
