RANDOM1:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    MAX: 5
    ID1: GAYGO1
    ID2: GAYGO2
    ID3: GAYGO3
    ID4: GAYGO4
    ID5: GAYGO5
RANDOM2:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    MAX: 5
    ID1: GAYGO3
    ID2: GAYGO4
    ID3: GAYGO5
    ID4: GAYGO6
    ID5: GAYGO7
RANDOM3:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    MAX: 5
    ID1: GAYGO5
    ID2: GAYGO6
    ID3: GAYGO7
    ID4: GAYGO8
    ID5: GAYGO9
RANDOM4:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    MAX: 5
    ID1: GAYGO7
    ID2: GAYGO8
    ID3: GAYGO9
    ID4: GAYGO10
    ID5: GAYGO11
RANDOM5:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    MAX: 5
    ID1: GAYGO9
    ID2: GAYGO10
    ID3: GAYGO11
    ID4: GAYGO12
    ID5: GAYGO13
RANDOM6:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    MAX: 5
    ID1: GAYGO11
    ID2: GAYGO12
    ID3: GAYGO13
    ID4: GAYGO14
    ID5: GAYGO15
RANDOM7:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    MAX: 5
    ID1: GAYGO13
    ID2: GAYGO14
    ID3: GAYGO15
    ID4: GAYGO16
    ID5: GAYGO17
RANDOM8:
  MATERIAL_TYPE: MATERIAL
  TYPE: WAND
  LIST:
    MAX: 5
    ID1: GAYGO15
    ID2: GAYGO16
    ID3: GAYGO17
    ID4: GAYGO18
    ID5: GAYGO19
