name: MythiccCore
version: '${project.version}'
main: net.danh.mythicccore.MythiccCore
api-version: 1.14
authors: [ VoChiDanh ]
depend: [ MythicMobs, MMOCore, ProtocolLib, PlaceholderAPI, MMOItems, MythicLib, RealisticSeasons ]
description: MythiccCore For RPGMythicc Project
commands:
  openregeneratorgui:
    description: openregeneratorgui
  MythiccCore:
    description: MythiccCore
  upgradegui:
    description: upgradegui
  soul:
    description: soul
  MythiccItems:
    description: MythiccItems
  namsinh:
    description: namsinh
