name: Development-Builds
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{github.repository}}
          separator: "/"
      - name: Discord Webhook
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "${{ steps.split.outputs._1 }}"
          embed-title: "Development Builds"
          avatar-url: "https://github.com/${{ steps.split.outputs._0 }}.png"
          embed-color: "65280"
          embed-description: |
            Change Log:
            
            ${{ github.event.head_commit.message }}
            
            Developer: [`${{ github.actor }}`](https://github.com/${{ github.actor }})

